### PR TITLE
add mc::BalanceEquation

### PR DESCRIPTION
**Pull request by notSam25**

### CODE REVIEW

**Comment by notSam25** [comment]
@theVerySharpFlat @ADawesomeguy if you guys could possibly help out with this, it would be appreciated.

**Comment by ADawesomeguy** [comment]
I already did lol

**Comment by notSam25** [comment]
> > I already did lol
> 
> The code in `src/Core/Util.hpp` still uses `48` instead of `'0'`.

Sure I can take a look through all the code, I'll start beautifying it for better readability and see if I can make it faster.

**Comment by ADawesomeguy** [comment]
> > I already did lol
> 
> The code in `src/Core/Util.hpp` still uses `48` instead of `'0'`.

@Ta180m I had it in a PR

**Comment by Ta180m** [comment]
> > > I already did lol
> > 
> > 
> > The code in `src/Core/Util.hpp` still uses `48` instead of `'0'`.
> 
> Sure I can take a look through all the code, I'll start beautifying it for better readability and see if I can make it faster.

It's CPP, it's already fast enough

**Comment by notSam25** [comment]
Finished this in main branch.

**Pull request closed without merging**
