### PR TITLE
refactor: add headers alongside source files

### PR DESCRIPTION
**Pull request by ADawesomeguy**
Sam is bad at not using only headers

### CODE REVIEW

**Comment by ADawesomeguy** [comment]
I also improved some style things (e.g. I made the namespace casing more consistent) as well as changed the use of `ghc::filesystem` to `std::filesystem`.

**Comment by theVerySharpFlat** [comment]
> I agree with the lowercase but I just followed Sam's naming scheme.

And you thought that was a good idea?

**Comment by ADawesomeguy** [comment]
> > std::filesystem can be linked properly on older compilers.
> 
> The header on older versions of clang and g++ is under experimental/filesystem and you have to link with the library. I know this because my machine at home is running opensuse leap 15.3 which has a version of clang and g++ that makes you do this

@theVerySharpFlat I added macros so it supports older compiles and includes the linker flag when necessary. Check https://github.com/notSam25/MultiChem/pull/12/commits/52b6cf1761bdfc8bb1cd9c0e65ca7d8b27ccfb5b.

**Comment by ADawesomeguy** [comment]
> > I agree with the lowercase but I just followed Sam's naming scheme.
> 
> And you thought that was a good idea?

No, but it could be a different PR.

**Comment by notSam25** [comment]
Just so you freaks know:
1) I used header files because I was just testing the functions. They would have eventualy been moved to *.cpp
2) All the function names and var names would be Adjusted in my latest PR.

**Comment by ADawesomeguy** [comment]
So merge this then, @notSam25?

**Review by notSam25 — APPROVED** [review]
Looks good, I'll merge!

**Pull request merged**
